name: Release

on:
  push:
    branches:
      - main
      
jobs:
  release:
    name: Release

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use PNPM v9.15.4
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js v20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: Install dependencies
        run: pnpm install

      - name: Generate release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # See: https://github.com/github/vscode-github-actions/issues/222
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: pnpm semantic-release